plugin: community.proxmox.proxmox
url: https://192.168.1.35:8006/
user: root@pam
password: "4355"
validate_certs: false
want_facts: true
want_proxmox_nodes_ansible_host: false

compose:
  ansible_host: (proxmox_agent_interfaces | selectattr('name', '!=', 'lo') | first)['ip-addresses'] | select('search', '\.') | first | split('/') | first
