---
- name: Configure K3s Master
  hosts: "{{ target_master }}"
  become: true
  tasks:
    - name: Initialize K3s cluster
      ansible.builtin.shell: /opt/k3s-install.sh
      environment:
        INSTALL_K3S_SKIP_DOWNLOAD: "true"
        INSTALL_K3S_EXEC: "server --cluster-init --node-name {{ inventory_hostname }} --tls-san {{ ansible_host }}"

    - name: Wait for node-token
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/node-token

    - name: Read node-token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Set master facts for workers to use
      ansible.builtin.set_fact:
        k3s_token: "{{ node_token['content'] | b64decode | trim }}"
        is_k3s_master: true


- name: Configure K3s Workers
  hosts: "{{ target_workers }}"
  become: true
  tasks:
    - name: Stop unintended K3s server service
      ansible.builtin.systemd:
        name: k3s
        state: stopped
        enabled: false
      failed_when: false

    - name: Look up Master node details
      ansible.builtin.set_fact:
        master_node: "{{ groups['all'] | map('extract', hostvars) | selectattr('is_k3s_master', 'defined') | first }}"

    - name: Join K3s cluster as Worker
      ansible.builtin.shell: /opt/k3s-install.sh
      environment:
        INSTALL_K3S_SKIP_DOWNLOAD: "true"
        K3S_URL: "https://{{ master_node.ansible_host }}:6443"
        K3S_TOKEN: "{{ master_node.k3s_token }}"
        INSTALL_K3S_EXEC: "agent --node-name {{ inventory_hostname }}"
